### ISSUE TITLE
Must manually assign context every time?

### ISSUE THREAD

**Issue by faceleg** [bkniffler/sequelize-revisions#1]
This module looks to be exactly what I need - a module to allow me to easily add change tracking to my models.

Reading through the docs, I see the "Get the current user" section - is this:

``` JS
model.context = { user: req.user }
```

Required if one wants revisions tracked? If I do not do this, will revision data be stored?

**Comment by bkniffler** [comment]
Sorry for the (very) late reply, I didn't see this issue.. 
As to the answer, it will still be tracked, just without any reference to the user!

**Comment by faceleg** [comment]
Thanks for the reply. I ended up using https://github.com/2ndQuadrant/audit-trigger

**Comment by bkniffler** [comment]
Hey, thats pretty nice! Thanks for letting me know, I'll definitely check it out.

**Comment by faceleg** [comment]
Harder to setup than this module, but as I have to do a lot of per field and per table searching and display results in a table, it suits my needs better.

sequelize-revisions is by far the best native-sequelize method I found though, thanks for sharing it!

**Comment by bkniffler** [comment]
Thanks, I appreciate your words!
